language: python
python:
  - "3.6"

services:
  - docker

git:
  depth: 3

before_install:
  - sudo -H apt-get update -qq
  - sudo -H apt-get install -qq python-apt python-pycurl

install:
  - sudo -H pip install http://releases.ansible.com/ansible/ansible-2.2.1.0.tar.gz
  - sudo -H pip install docker-py==1.10.6
  - sudo -H pip install netaddr==0.7.19
  - echo -e 'localhost  ansible_connection=local' > tests/inventory
  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./tests/inventory' > ansible.cfg

script:
  - ansible-playbook --syntax-check tests/role.yml
  - ansible-playbook -v --diff tests/role.yml
  - >
    ansible-playbook tests/role.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
